**************************************************************************************************************
Filename: example11.pdb
Date/time: Mon Dec 15 19:07:47 2008
Reference base-pair: 11.00
Zone: start 1 end 20
**************************************************************************************************************
Global bend angles of individual base-pair steps and of all identified base-pair steps together:
frac. tilt    = contribution of tilt to the base-pair step bending angle
frac. roll    = contribution of roll to the base-pair step bending angle
bp-step angle = bending angle (deg.) at each base-pair step.
orient angle  = orientation of the bend angle relative to the reference base-pair in Euler-angle
                space (from 0 to 360 deg.)
global tilt   = the value of Tilt (deg.) in the global reference frame.
global roll   = the value of Roll (deg.) in the global reference frame.
Acc. twist    = accumulated twist values (deg.) above and below the reference base-pair.
x	          = If the reference plane is located between two basepairs, one base-pair is
		       duplicated for the calculation (two x's). If the reference plane coincides with
		       one base-pair no duplication is necessary (one x)

index  bp-step  frac.tilt   frac.roll   bp-step angle orient angle global tilt  global roll  Acc.twist  refbp
 1       T-A      0.018       0.982        0.000       88.947         0.000        0.000      322.790    
 2       G-C      0.285       0.715        2.883       73.428         1.540        2.437      322.790    
 3       C-G      0.648       0.352        3.172       49.627         2.553        1.883      287.700    
 4       A-T      0.337       0.663        3.131       70.290         1.819        2.549      249.700    
 5       A-T      0.717       0.283        2.939       44.181         2.489        1.563      214.620    
 6       T-A      0.490       0.510        3.253       60.682         2.276        2.324      178.660    
 7       T-A      0.282       0.718        2.890       73.598         1.536        2.448      142.980    
 8       G-C      0.643       0.357        3.176       49.980         2.547        1.898      107.020    
 9       C-G      0.353       0.647        3.169       69.346         1.882        2.550       71.930    
10       G-C      0.718       0.282        2.955       44.139         2.503        1.570       33.940    
11       T-A      0.502       0.498        3.246       59.856         2.300        2.290        0.000   x
12       G-C      0.285       0.715        2.936       73.433         1.568        2.482      -35.090    
13       C-G      0.639       0.361        3.170       50.300         2.534        1.905      -73.090    
14       A-T      0.352       0.648        3.155       69.415         1.871        2.540     -108.180    
15       A-T      0.712       0.288        2.927       44.638         2.469        1.572     -144.140    
16       T-A      0.503       0.497        3.239       59.780         2.298        2.282     -179.810    
17       T-A      0.286       0.714        2.921       73.391         1.562        2.468     -215.770    
18       G-C      0.649       0.351        3.157       49.512         2.544        1.869     -250.860    
19       C-G      0.349       0.651        3.146       69.547         1.860        2.537     -288.860    
20       G-C      0.711       0.289        2.889       44.705         2.435        1.554     -322.790    

sum.              9.479      10.521       58.352     1218.795        40.583       40.723      313.540
ave.              0.474       0.526        2.918       60.940         2.029        2.036       15.677
S.D.              0.174       0.174        0.139       11.731         0.400        0.388      201.938

The global bend-angle     = 57.492
**************************************************************************************************************
